In [15]:
import numpy as np

In [60]:
problem = '''
-35-9--48
--9--8--3
-4-6-5--1
----74---
-2-----6-
---15----
8--9-2-7-
9--5--2--
61--4-53-
'''
problem = [list(l) for l in problem.split('\n') if l != '']
problem = [0 if c == '-' else int(c) for l in problem for c in l]
problem = np.asarray(problem, dtype='int32').reshape((9, 9))

In [64]:
def sudoku_solve(problem):
    rows, cols = problem.shape
    nums = set([i for i in range(0, 10)])
    for i in range(rows):
        for j in range(cols):
            if problem[i, j] == 0:
                k = i // 3
                l = j // 3
                row_nums = problem[i, :].tolist()
                col_nums = problem[:, j].tolist()
                blk_nums = problem[3*k:3*k+3, 3*l:3*l+3].reshape(-1).tolist()
                used = set(row_nums + col_nums + blk_nums)
                diff = nums.difference(used)
                if len(diff) == 0:
                    return False
                
                success = False
                for n in diff:
                    problem[i, j] = n
                    if dfs(problem):
                        success = True
                        break

                    problem[i, j] = 0

                if not success:
                    return False
        
    return True

In [65]:
dfs(problem)

True

In [66]:
print(problem)

[[2 3 5 7 9 1 6 4 8]
 [1 6 9 4 2 8 7 5 3]
 [7 4 8 6 3 5 9 2 1]
 [3 9 6 2 7 4 8 1 5]
 [5 2 1 3 8 9 4 6 7]
 [4 8 7 1 5 6 3 9 2]
 [8 5 3 9 6 2 1 7 4]
 [9 7 4 5 1 3 2 8 6]
 [6 1 2 8 4 7 5 3 9]]
